name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  ESLint:
    name: ESLint

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install
      run: npm install -g eslint
    - name: Script
      run: eslint --report-unused-disable-directives .
      continue-on-error: true

  TSC:
    name: TypeScript Compiler

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-node@v3
    - name: Install
      run: npm install -g typescript
    - name: Script
      run: tsc -p jsconfig.json --noEmit
      continue-on-error: true
